//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LH.Forcas.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LH.Forcas.Localization.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string AccountsDetailPage_AccountType {
            get {
                return ResourceManager.GetString("AccountsDetailPage_AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string AccountsDetailPage_Bank {
            get {
                return ResourceManager.GetString("AccountsDetailPage_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Connection.
        /// </summary>
        public static string AccountsDetailPage_BankSectionTitle {
            get {
                return ResourceManager.GetString("AccountsDetailPage_BankSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string AccountsDetailPage_Country {
            get {
                return ResourceManager.GetString("AccountsDetailPage_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading the account. If this happens again, please report it at our website..
        /// </summary>
        public static string AccountsDetailPage_LoadError {
            get {
                return ResourceManager.GetString("AccountsDetailPage_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AccountsDetailPage_Name {
            get {
                return ResourceManager.GetString("AccountsDetailPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem saving the account. If this happens again, please report it at our website..
        /// </summary>
        public static string AccountsDetailPage_SaveError {
            get {
                return ResourceManager.GetString("AccountsDetailPage_SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account.
        /// </summary>
        public static string AccountsDetailPage_Title_New {
            get {
                return ResourceManager.GetString("AccountsDetailPage_Title_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the account {0} and all related transactions?.
        /// </summary>
        public static string AccountsListPage_DeleteAccountConfirmMsgFormat {
            get {
                return ResourceManager.GetString("AccountsListPage_DeleteAccountConfirmMsgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account?.
        /// </summary>
        public static string AccountsListPage_DeleteAccountConfirmTitle {
            get {
                return ResourceManager.GetString("AccountsListPage_DeleteAccountConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re really sorry, but an error occured while deleting the account. If this happens again, please report it at our website..
        /// </summary>
        public static string AccountsListPage_DeleteAccountError {
            get {
                return ResourceManager.GetString("AccountsListPage_DeleteAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last synced {0}.
        /// </summary>
        public static string AccountsListPage_LastSyncLabelFormat {
            get {
                return ResourceManager.GetString("AccountsListPage_LastSyncLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsListPage_Title {
            get {
                return ResourceManager.GetString("AccountsListPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your checking or other account in a bank we will connect to and download the transactions..
        /// </summary>
        public static string AccountType_Bank_Description {
            get {
                return ResourceManager.GetString("AccountType_Bank_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string AccountType_BankAccount {
            get {
                return ResourceManager.GetString("AccountType_BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To track the balance of your wallet or money you have under the pillow....
        /// </summary>
        public static string AccountType_Cash_Description {
            get {
                return ResourceManager.GetString("AccountType_Cash_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string AccountType_CashAccount {
            get {
                return ResourceManager.GetString("AccountType_CashAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any kind of money you own to anyone, like mortgage, car loan and similar.
        /// </summary>
        public static string AccountType_Loan_Description {
            get {
                return ResourceManager.GetString("AccountType_Loan_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan.
        /// </summary>
        public static string AccountType_LoanAccount {
            get {
                return ResourceManager.GetString("AccountType_LoanAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string AlertDialog_ErrorTitle {
            get {
                return ResourceManager.GetString("AlertDialog_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AlertDialog_OK {
            get {
                return ResourceManager.GetString("AlertDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ConfirmDialog_No {
            get {
                return ResourceManager.GetString("ConfirmDialog_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ConfirmDialog_Yes {
            get {
                return ResourceManager.GetString("ConfirmDialog_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going away will undo the changes you have done, do you want to continue?.
        /// </summary>
        public static string ConfirmDirtyDialog_Description {
            get {
                return ResourceManager.GetString("ConfirmDirtyDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really?.
        /// </summary>
        public static string ConfirmDirtyDialog_Title {
            get {
                return ResourceManager.GetString("ConfirmDirtyDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a day ago.
        /// </summary>
        public static string DateTimeAgo_Day {
            get {
                return ResourceManager.GetString("DateTimeAgo_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string DateTimeAgo_Days {
            get {
                return ResourceManager.GetString("DateTimeAgo_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an hour ago.
        /// </summary>
        public static string DateTimeAgo_Hour {
            get {
                return ResourceManager.GetString("DateTimeAgo_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string DateTimeAgo_Hours {
            get {
                return ResourceManager.GetString("DateTimeAgo_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one minute ago.
        /// </summary>
        public static string DateTimeAgo_Minute {
            get {
                return ResourceManager.GetString("DateTimeAgo_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string DateTimeAgo_Minutes {
            get {
                return ResourceManager.GetString("DateTimeAgo_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a month ago.
        /// </summary>
        public static string DateTimeAgo_Month {
            get {
                return ResourceManager.GetString("DateTimeAgo_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        public static string DateTimeAgo_Months {
            get {
                return ResourceManager.GetString("DateTimeAgo_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a few seconds ago.
        /// </summary>
        public static string DateTimeAgo_Seconds {
            get {
                return ResourceManager.GetString("DateTimeAgo_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a week ago.
        /// </summary>
        public static string DateTimeAgo_Week {
            get {
                return ResourceManager.GetString("DateTimeAgo_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weeks ago.
        /// </summary>
        public static string DateTimeAgo_Weeks {
            get {
                return ResourceManager.GetString("DateTimeAgo_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a year ago.
        /// </summary>
        public static string DateTimeAgo_Year {
            get {
                return ResourceManager.GetString("DateTimeAgo_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        public static string DateTimeAgo_Years {
            get {
                return ResourceManager.GetString("DateTimeAgo_Years", resourceCulture);
            }
        }
    }
}
